Repository dev-hooon/catchtable, pull requests merged in 2023-12, with the labels that each got.

#2 feat : 엔티티 세팅
  src/main/java/com/prgrms/catchtable/CatchtableApplication.java
  src/main/java/com/prgrms/catchtable/common/BaseEntity.java
  src/main/java/com/prgrms/catchtable/member/domain/Gender.java
  src/main/java/com/prgrms/catchtable/member/domain/Member.java
  src/main/java/com/prgrms/catchtable/member/repository/MemberRepository.java
  src/main/java/com/prgrms/catchtable/notification/domain/NotificationMember.java
  src/main/java/com/prgrms/catchtable/notification/domain/NotificationOwner.java
  src/main/java/com/prgrms/catchtable/notification/repository/NotificationMemberRepository.java
  src/main/java/com/prgrms/catchtable/notification/repository/NotificationOwnerRepository.java
  src/main/java/com/prgrms/catchtable/owner/domain/Owner.java
  src/main/java/com/prgrms/catchtable/owner/repository/OwnerRepository.java
  src/main/java/com/prgrms/catchtable/reservation/domain/Reservation.java
  src/main/java/com/prgrms/catchtable/reservation/domain/ReservationStatus.java
  src/main/java/com/prgrms/catchtable/reservation/domain/ReservationTime.java
  src/main/java/com/prgrms/catchtable/shop/domain/Address.java
  src/main/java/com/prgrms/catchtable/shop/domain/Category.java
  src/main/java/com/prgrms/catchtable/shop/domain/Menu.java
  src/main/java/com/prgrms/catchtable/shop/domain/Shop.java
  src/main/java/com/prgrms/catchtable/shop/repository/ShopRepository.java
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
Labels: feature

#13 fix : SQL 예약어 관련 오류 수정
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
Labels: fix

#11 feat: RestDocs 환경 세팅하기
  build.gradle
  src/test/java/com/prgrms/catchtable/CatchtableApplicationTests.java
  src/test/java/com/prgrms/catchtable/common/restdocs/RestDocsSupport.java
Labels: feature, chore

#5 chore : test container 의존성 추가
  build.gradle
Labels: chore

#16 chore : CI 구축하기
  .github/workflows/ci.yml
Labels: chore

#14 feat : 커스텀 예외 템플릿 생성
  src/main/java/com/prgrms/catchtable/common/exception/CommonException.java
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/common/exception/ExceptionHandler.java
  src/main/java/com/prgrms/catchtable/common/exception/custom/BadRequestCustomException.java
  src/main/java/com/prgrms/catchtable/common/exception/custom/NotFoundCustomException.java
Labels: feature

#25 fix : indent 오류 수정
  src/test/resources/application.yaml
Labels: fix

#23 feat : 예약 선점 로직 구현
  build.gradle
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/facade/ReservationFacade.java
  src/main/java/com/prgrms/catchtable/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/domain/Reservation.java
  src/main/java/com/prgrms/catchtable/reservation/domain/ReservationTime.java
  src/main/java/com/prgrms/catchtable/reservation/dto/request/CreateReservationRequest.java
  src/main/java/com/prgrms/catchtable/reservation/dto/response/CreateReservationResponse.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationAsync.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationService.java
  src/test/java/com/prgrms/catchtable/common/data/reservation/ReservationData.java
  src/test/java/com/prgrms/catchtable/common/data/shop/ShopData.java
  src/test/java/com/prgrms/catchtable/facade/ReservationFacadeTest.java
  src/test/java/com/prgrms/catchtable/reservation/domain/ReservationTimeTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: feature

#26 feat : 웨이팅 생성 로직 구현
  src/docs/asciidoc/api/album/waiting.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/catchtable/common/BaseEntity.java
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/common/exception/ExceptionHandler.java
  src/main/java/com/prgrms/catchtable/shop/domain/Shop.java
  src/main/java/com/prgrms/catchtable/waiting/controller/WaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
  src/main/java/com/prgrms/catchtable/waiting/domain/WaitingStatus.java
  src/main/java/com/prgrms/catchtable/waiting/dto/CreateWaitingRequest.java
  src/main/java/com/prgrms/catchtable/waiting/dto/CreateWaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingService.java
  src/test/java/com/prgrms/catchtable/member/MemberFixture.java
  src/test/java/com/prgrms/catchtable/shop/domain/ShopTest.java
  src/test/java/com/prgrms/catchtable/shop/fixture/ShopFixture.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/WaitingServiceTest.java
Labels: feature
