Repository dev-hooon/catchtable, pull requests merged in 2024-01, with the labels that each got.

#35 fix : merge conflict & CI Build Test Fail 해결
  build.gradle
  src/test/java/com/prgrms/catchtable/member/MemberFixture.java
Labels: fix

#27 feat : 예약 선점 api 구현 및 통합테스트
  build.gradle
  src/main/java/com/prgrms/catchtable/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/dto/response/CreateReservationResponse.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationAsync.java
  src/test/java/com/prgrms/catchtable/common/base/BaseIntegrationTest.java
  src/test/java/com/prgrms/catchtable/common/data/reservation/ReservationData.java
  src/test/java/com/prgrms/catchtable/facade/ReservationFacadeTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: feature

#33 feat : 예약 최종 등록 로직 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/common/exception/ErrorResponse.java
  src/main/java/com/prgrms/catchtable/common/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/catchtable/facade/ReservationFacade.java
  src/main/java/com/prgrms/catchtable/reservation/dto/mapper/ReservationMapper.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationService.java
  src/main/java/com/prgrms/catchtable/shop/domain/Shop.java
  src/main/java/com/prgrms/catchtable/waiting/domain/WaitingStatus.java
  src/main/java/com/prgrms/catchtable/waiting/dto/CreateWaitingRequest.java
  src/main/java/com/prgrms/catchtable/waiting/dto/CreateWaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingService.java
  src/test/java/com/prgrms/catchtable/common/data/reservation/ReservationData.java
  src/test/java/com/prgrms/catchtable/member/MemberFixture.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
  src/test/java/com/prgrms/catchtable/shop/domain/ShopTest.java
  src/test/java/com/prgrms/catchtable/shop/fixture/ShopFixture.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
Labels: feature

#40 fix : 테스트용 데이터 관련 빌드 오류 수정
  src/test/java/com/prgrms/catchtable/common/data/reservation/ReservationData.java
  src/test/java/com/prgrms/catchtable/facade/ReservationFacadeTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: fix

#43 feat : 예약 등록 API 구현
  src/main/java/com/prgrms/catchtable/reservation/controller/ReservationController.java
  src/test/java/com/prgrms/catchtable/common/base/BaseIntegrationTest.java
  src/test/java/com/prgrms/catchtable/facade/ReservationFacadeTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/domain/ReservationTimeTest.java
  src/test/java/com/prgrms/catchtable/reservation/fixture/ReservationFixture.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: feature

#41 대기 생성 API 수정 및 보완
  src/docs/asciidoc/api/album/waiting.adoc
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/waiting/controller/WaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingService.java
  src/test/java/com/prgrms/catchtable/member/MemberFixture.java
  src/test/java/com/prgrms/catchtable/shop/domain/ShopTest.java
  src/test/java/com/prgrms/catchtable/shop/fixture/ShopFixture.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/fixture/WaitingFixture.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/WaitingServiceTest.java
Labels: feature

#45 feat : 예약 조회 로직 구현
  src/main/java/com/prgrms/catchtable/reservation/domain/Reservation.java
  src/main/java/com/prgrms/catchtable/reservation/dto/mapper/ReservationMapper.java
  src/main/java/com/prgrms/catchtable/reservation/dto/response/GetAllReservationResponse.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationService.java
  src/test/java/com/prgrms/catchtable/reservation/fixture/ReservationFixture.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: feature

#48 refactor : 퍼사드 계층 제거
  src/main/java/com/prgrms/catchtable/facade/ReservationFacade.java
  src/main/java/com/prgrms/catchtable/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationLockRepository.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationService.java
  src/test/java/com/prgrms/catchtable/facade/ReservationFacadeTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: refactor

#51 feat : Jwt 관련 테스트
  src/main/java/com/prgrms/catchtable/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/catchtable/security/config/SecurityConfig.java
  src/main/java/com/prgrms/catchtable/security/controller/TestController.java
  src/test/java/com/prgrms/catchtable/jwt/provider/JwtTokenProviderTest.java
  src/test/java/com/prgrms/catchtable/jwt/service/JwtUserDetailsServiceTest.java
  src/test/java/com/prgrms/catchtable/jwt/service/RefreshTokenServiceTest.java
  src/test/java/com/prgrms/catchtable/security/controller/JwtAuthenticationTest.java
Labels: feature

#53 feat : 웨이팅 queue 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationService.java
  src/main/java/com/prgrms/catchtable/security/config/SecurityConfig.java
  src/main/java/com/prgrms/catchtable/security/controller/TestController.java
  src/main/java/com/prgrms/catchtable/waiting/config/RedisConfig.java
  src/main/java/com/prgrms/catchtable/waiting/controller/WaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/WaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingService.java
  src/test/java/com/prgrms/catchtable/jwt/service/JwtUserDetailsServiceTest.java
  src/test/java/com/prgrms/catchtable/security/controller/JwtAuthenticationTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/WaitingServiceTest.java
  src/test/resources/application.yaml
Labels: feature

#54 feat : 예약 수정 API 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/reservation/controller/ReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/domain/Reservation.java
  src/main/java/com/prgrms/catchtable/reservation/dto/mapper/ReservationMapper.java
  src/main/java/com/prgrms/catchtable/reservation/dto/request/ModifyReservationRequest.java
  src/main/java/com/prgrms/catchtable/reservation/dto/response/ModifyReservationResponse.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationService.java
  src/test/java/com/prgrms/catchtable/reservation/controller/ReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/domain/ReservationTest.java
  src/test/java/com/prgrms/catchtable/reservation/fixture/ReservationFixture.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/ReservationServiceTest.java
Labels: feature

#62 feat : 웨이팅 생성 API Redis queue 사용하도록 수정
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/WaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingService.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/WaitingServiceTest.java
Labels: feature

#66 feat : 대기 순서 지연 API 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/waiting/controller/WaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingService.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/WaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/WaitingServiceTest.java
Labels: feature

#70 feat : 대기 취소, 대기 조회 API 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/waiting/controller/MemberWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
  src/main/java/com/prgrms/catchtable/waiting/domain/WaitingStatus.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/MemberWaitingService.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/MemberWaitingServiceTest.java
Labels: feature

#60 feat : Owner 회원가입 & 로그인 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/member/domain/Gender.java
  src/main/java/com/prgrms/catchtable/owner/controller/OwnerController.java
  src/main/java/com/prgrms/catchtable/owner/domain/Owner.java
  src/main/java/com/prgrms/catchtable/owner/dto/OwnerMapper.java
  src/main/java/com/prgrms/catchtable/owner/dto/request/JoinOwnerRequest.java
  src/main/java/com/prgrms/catchtable/owner/dto/request/LoginOwnerRequest.java
  src/main/java/com/prgrms/catchtable/owner/dto/response/JoinOwnerResponse.java
  src/main/java/com/prgrms/catchtable/owner/repository/OwnerRepository.java
  src/main/java/com/prgrms/catchtable/owner/service/OwnerService.java
  src/main/java/com/prgrms/catchtable/security/config/SecurityConfig.java
  src/test/java/com/prgrms/catchtable/common/base/BaseIntegrationTest.java
  src/test/java/com/prgrms/catchtable/owner/controller/OwnerControllerTest.java
  src/test/java/com/prgrms/catchtable/owner/fixture/OwnerFixture.java
  src/test/java/com/prgrms/catchtable/owner/service/OwnerServiceTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/OwnerReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/OwnerReservationServiceTest.java
Labels: feature

#68 feat : 예약 수정 로직 추가
  src/main/java/com/prgrms/catchtable/reservation/domain/ReservationTime.java
  src/main/java/com/prgrms/catchtable/reservation/service/MemberReservationService.java
  src/main/java/com/prgrms/catchtable/reservation/service/OwnerReservationService.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceTest.java
Labels: feature

#77 feat : 회원의 예약 전체조회 api 추가 및 테스트
  src/main/java/com/prgrms/catchtable/reservation/controller/MemberReservationController.java
  src/test/java/com/prgrms/catchtable/owner/controller/OwnerControllerTest.java
  src/test/java/com/prgrms/catchtable/owner/fixture/OwnerFixture.java
  src/test/java/com/prgrms/catchtable/owner/service/OwnerServiceTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/OwnerReservationControllerTest.java
Labels: feature

#78 refactor : 선점여부, 예약여부 바꾸는 메소드 변경
  src/main/java/com/prgrms/catchtable/reservation/domain/ReservationTime.java
  src/main/java/com/prgrms/catchtable/reservation/service/MemberReservationService.java
  src/main/java/com/prgrms/catchtable/reservation/service/OwnerReservationService.java
  src/main/java/com/prgrms/catchtable/reservation/service/ReservationAsync.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/OwnerReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/domain/ReservationTimeTest.java
  src/test/java/com/prgrms/catchtable/reservation/fixture/ReservationFixture.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceIntegrationTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceTest.java
Labels: feature

#81 feat : 현재 로그인 정보 조회 어노테이션 추가 (@LogIn)
  src/main/java/com/prgrms/catchtable/common/login/LogIn.java
  src/main/java/com/prgrms/catchtable/common/login/LogInArgumentResolver.java
  src/main/java/com/prgrms/catchtable/common/login/WebConfig.java
Labels: feature

#80 feat : JWT에 권한을 함께 넣어준다.
  src/main/java/com/prgrms/catchtable/common/Role.java
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/jwt/domain/RefreshToken.java
  src/main/java/com/prgrms/catchtable/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/catchtable/jwt/provider/JwtTokenProvider.java
  src/main/java/com/prgrms/catchtable/jwt/service/JwtUserDetailsService.java
  src/main/java/com/prgrms/catchtable/jwt/service/RefreshTokenService.java
  src/main/java/com/prgrms/catchtable/jwt/token/Token.java
  src/main/java/com/prgrms/catchtable/member/domain/Gender.java
  src/main/java/com/prgrms/catchtable/member/service/MemberService.java
  src/main/java/com/prgrms/catchtable/owner/service/OwnerService.java
  src/test/java/com/prgrms/catchtable/jwt/provider/JwtTokenProviderTest.java
  src/test/java/com/prgrms/catchtable/jwt/service/JwtUserDetailsServiceTest.java
  src/test/java/com/prgrms/catchtable/jwt/service/RefreshTokenServiceTest.java
  src/test/java/com/prgrms/catchtable/owner/controller/OwnerControllerTest.java
  src/test/java/com/prgrms/catchtable/owner/service/OwnerServiceTest.java
  src/test/java/com/prgrms/catchtable/security/controller/JwtAuthenticationTest.java
Labels: fix

#82 feat : 유저 웨이팅 입장 API 구현
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/WaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/OwnerWaitingService.java
  src/test/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/OwnerWaitingServiceTest.java
Labels: feature

#87 feat : 예약과 회원 연관관계 매핑
  src/main/java/com/prgrms/catchtable/common/login/WebConfig.java
  src/main/java/com/prgrms/catchtable/reservation/controller/MemberReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/domain/Reservation.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/catchtable/reservation/service/MemberReservationService.java
  src/test/java/com/prgrms/catchtable/common/base/BaseIntegrationTest.java
  src/test/java/com/prgrms/catchtable/owner/service/OwnerServiceTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/fixture/ReservationFixture.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceIntegrationTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceTest.java
Labels: feature

#93 feat : 예약 알림 기능 추가
  src/main/java/com/prgrms/catchtable/common/notification/NotificationContent.java
  src/main/java/com/prgrms/catchtable/common/notification/NotificationEvent.java
  src/main/java/com/prgrms/catchtable/notification/dto/request/SendMessageToMemberRequest.java
  src/main/java/com/prgrms/catchtable/notification/dto/request/SendMessageToOwnerRequest.java
  src/main/java/com/prgrms/catchtable/notification/service/NotificationService.java
  src/main/java/com/prgrms/catchtable/owner/domain/Owner.java
  src/main/java/com/prgrms/catchtable/owner/repository/OwnerRepository.java
  src/main/java/com/prgrms/catchtable/reservation/controller/MemberReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/service/MemberReservationService.java
  src/test/java/com/prgrms/catchtable/owner/repository/OwnerRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceTest.java
Labels: feature

#96 feat : 웨이팅 스케줄러 구현
  src/docs/asciidoc/api/album/waiting.adoc
  src/docs/asciidoc/api/waiting/waiting.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/catchtable/waiting/controller/MemberWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/domain/Waiting.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/schedular/WaitingScheduler.java
  src/main/java/com/prgrms/catchtable/waiting/service/MemberWaitingService.java
  src/main/java/com/prgrms/catchtable/waiting/service/OwnerWaitingService.java
  src/test/java/com/prgrms/catchtable/common/restdocs/RestDocsConfig.java
  src/test/java/com/prgrms/catchtable/common/restdocs/RestDocsSupport.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/schedular/WaitingSchedulerTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/MemberWaitingServiceTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/OwnerWaitingServiceTest.java
Labels: feature

#99 feat : Rest Docs 명세화
  src/docs/asciidoc/api/waiting/waiting.adoc
  src/main/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/dto/WaitingMapper.java
  src/main/java/com/prgrms/catchtable/waiting/dto/response/MemberWaitingHistoryListResponse.java
  src/main/java/com/prgrms/catchtable/waiting/dto/response/MemberWaitingHistoryResponse.java
  src/main/java/com/prgrms/catchtable/waiting/dto/response/OwnerWaitingResponse.java
  src/main/java/com/prgrms/catchtable/waiting/service/OwnerWaitingService.java
  src/test/java/com/prgrms/catchtable/common/restdocs/RestDocsSupport.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/fixture/WaitingFixture.java
  src/test/java/com/prgrms/catchtable/waiting/service/MemberWaitingServiceTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/OwnerWaitingServiceTest.java
Labels: feature

#97 feat : 예약 api REST Docs 명세
  src/main/java/com/prgrms/catchtable/reservation/controller/OwnerReservationController.java
  src/main/java/com/prgrms/catchtable/reservation/service/OwnerReservationService.java
  src/test/java/com/prgrms/catchtable/common/restdocs/RestDocsSupport.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/OwnerReservationControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/OwnerReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/OwnerReservationServiceTest.java
Labels: feature

#101 feat : 예약 사전 알림 기능 추가
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/catchtable/reservation/scheduler/ReservationNotificationScheduler.java
  src/main/java/com/prgrms/catchtable/reservation/scheduler/SchedulerConfig.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationRepositoryTest.java
Labels: feature

#95 feat : Shop 등록 & 조회
  .gitignore
  build.gradle
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/notification/service/NotificationService.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/prgrms/catchtable/shop/controller/MemberShopController.java
  src/main/java/com/prgrms/catchtable/shop/controller/OwnerShopController.java
  src/main/java/com/prgrms/catchtable/shop/domain/Category.java
  src/main/java/com/prgrms/catchtable/shop/domain/Menu.java
  src/main/java/com/prgrms/catchtable/shop/domain/Shop.java
  src/main/java/com/prgrms/catchtable/shop/dto/ShopMapper.java
  src/main/java/com/prgrms/catchtable/shop/dto/request/RegisterMenuRequest.java
  src/main/java/com/prgrms/catchtable/shop/dto/request/RegisterShopRequest.java
  src/main/java/com/prgrms/catchtable/shop/dto/request/ShopSearchCondition.java
  src/main/java/com/prgrms/catchtable/shop/dto/response/GetAllShopResponse.java
  src/main/java/com/prgrms/catchtable/shop/dto/response/GetAllShopResponses.java
  src/main/java/com/prgrms/catchtable/shop/dto/response/GetShopResponse.java
  src/main/java/com/prgrms/catchtable/shop/dto/response/MenuResponse.java
  src/main/java/com/prgrms/catchtable/shop/dto/response/RegisterShopResponse.java
  src/main/java/com/prgrms/catchtable/shop/dto/response/ReservationTimeResponse.java
  src/main/java/com/prgrms/catchtable/shop/repository/ShopRepository.java
  src/main/java/com/prgrms/catchtable/shop/repository/ShopRepositoryCustom.java
  src/main/java/com/prgrms/catchtable/shop/repository/ShopRepositoryImpl.java
  src/main/java/com/prgrms/catchtable/shop/service/MemberShopService.java
  src/main/java/com/prgrms/catchtable/shop/service/OwnerShopService.java
  src/test/java/com/prgrms/catchtable/common/base/BaseIntegrationTest.java
  src/test/java/com/prgrms/catchtable/owner/controller/OwnerControllerTest.java
  src/test/java/com/prgrms/catchtable/owner/fixture/OwnerFixture.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceTest.java
  src/test/java/com/prgrms/catchtable/shop/controller/MemberShopControllerTest.java
  src/test/java/com/prgrms/catchtable/shop/controller/OwnerShopControllerTest.java
  src/test/java/com/prgrms/catchtable/shop/fixture/ShopFixture.java
  src/test/java/com/prgrms/catchtable/shop/repository/ShopRepositoryTest.java
  src/test/java/com/prgrms/catchtable/shop/service/ShopServiceTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingControllerTest.java
Labels: feature

#103 feature : 웨이팅 알림 기능 구현
  src/docs/asciidoc/api/waiting/waiting.adoc
  src/main/java/com/prgrms/catchtable/common/exception/ErrorCode.java
  src/main/java/com/prgrms/catchtable/common/notification/WaitingNotificationContent.java
  src/main/java/com/prgrms/catchtable/waiting/controller/MemberWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingController.java
  src/main/java/com/prgrms/catchtable/waiting/domain/WaitingStatus.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/waitingline/WaitingLineRepository.java
  src/main/java/com/prgrms/catchtable/waiting/service/MemberWaitingService.java
  src/main/java/com/prgrms/catchtable/waiting/service/OwnerWaitingService.java
  src/main/java/com/prgrms/catchtable/waiting/service/WaitingNotification.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingControllerDocsTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/OwnerWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/fixture/WaitingFixture.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/BasicWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/waitingline/RedisWaitingLineRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/MemberWaitingServiceTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/OwnerWaitingServiceTest.java
Labels: feature

#111 feat : Owner logout 기능 구현
  src/main/java/com/prgrms/catchtable/jwt/service/RefreshTokenService.java
  src/main/java/com/prgrms/catchtable/owner/controller/OwnerController.java
  src/main/java/com/prgrms/catchtable/owner/service/OwnerService.java
  src/test/java/com/prgrms/catchtable/owner/service/OwnerServiceTest.java
Labels: feature

#109 feature : 웨이팅 생성 시 동시성 구현하기
  src/main/java/com/prgrms/catchtable/shop/domain/Shop.java
  src/main/java/com/prgrms/catchtable/shop/repository/ShopRepository.java
  src/main/java/com/prgrms/catchtable/waiting/repository/WaitingRepository.java
  src/main/java/com/prgrms/catchtable/waiting/schedular/WaitingScheduler.java
  src/main/java/com/prgrms/catchtable/waiting/service/MemberWaitingService.java
  src/test/java/com/prgrms/catchtable/shop/repository/ShopRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/controller/MemberWaitingControllerTest.java
  src/test/java/com/prgrms/catchtable/waiting/repository/WaitingRepositoryTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/MemberWaitingServiceIntegrationTest.java
  src/test/java/com/prgrms/catchtable/waiting/service/MemberWaitingServiceTest.java
Labels: feature

#112 feat : Member login & logout 기능 구현
  src/main/java/com/prgrms/catchtable/member/controller/MemberController.java
  src/main/java/com/prgrms/catchtable/member/service/MemberService.java
Labels: feature

#114 feat : 예약 dto mapper 수정
  src/docs/asciidoc/api/waiting/waiting.adoc
  src/main/java/com/prgrms/catchtable/jwt/service/RefreshTokenService.java
  src/main/java/com/prgrms/catchtable/member/controller/MemberController.java
  src/main/java/com/prgrms/catchtable/member/service/MemberService.java
  src/main/java/com/prgrms/catchtable/owner/controller/OwnerController.java
  src/main/java/com/prgrms/catchtable/owner/service/OwnerService.java
  src/main/java/com/prgrms/catchtable/reservation/dto/mapper/ReservationMapper.java
  src/main/java/com/prgrms/catchtable/reservation/repository/ReservationRepository.java
  src/main/java/com/prgrms/catchtable/shop/domain/Shop.java
  src/test/java/com/prgrms/catchtable/reservation/controller/MemberReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/controller/OwnerReservationControllerTest.java
  src/test/java/com/prgrms/catchtable/reservation/fixture/ReservationFixture.java
  src/test/java/com/prgrms/catchtable/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/prgrms/catchtable/reservation/service/MemberReservationServiceTest.java
Labels: feature

#117 chore: RestDocs 예약 API 반영
  src/docs/asciidoc/api/reservation/reservation.adoc
  src/docs/asciidoc/index.adoc
Labels: chore
